baseUrl: '@web/de'
enabled: true
handle: happyLagerDe
hasUrls: true
language: de
name: 'Happy Lager (de)'
primary: false
siteGroup: 268c3c49-6715-4b6a-a1b9-f27313adabd1 # Happy Lager (en)
sortOrder: 3
