defaultPlacement: end
enableVersioning: true
handle: servicesIndex
name: 'Services Index'
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  06f4e499-3cdc-4d64-aec2-9a7d3a143c75: # Happy Lager (en)
    enabledByDefault: true
    hasUrls: true
    template: services/_index
    uriFormat: services
  751575f8-99dd-42c4-a5f8-69e48773ad7f: # Happy Lager (es)
    enabledByDefault: true
    hasUrls: true
    template: services/_index
    uriFormat: services
  b50df2c6-3c2c-4215-b2a6-60926c2559e3: # Happy Lager (de)
    enabledByDefault: true
    hasUrls: true
    template: services/_index
    uriFormat: services
type: single
